// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRYZ_og5oOMFoUjH3sAm-arMeN8sxCJ0',
    appId: '1:785012893388:web:0bcc46ae7d002716748469',
    messagingSenderId: '785012893388',
    projectId: 'social-circle-qa',
    authDomain: 'social-circle-qa.firebaseapp.com',
    storageBucket: 'social-circle-qa.appspot.com',
    measurementId: 'G-8WPJ70PGCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl_VsSGWJZg-h8wEdtfsr9d3BmTxj-KGw',
    appId: '1:785012893388:android:6c6f72ba87313361748469',
    messagingSenderId: '785012893388',
    projectId: 'social-circle-qa',
    storageBucket: 'social-circle-qa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA1l0CsYs_EDH9QVIxAMf_Ht4iEixUfiE',
    appId: '1:785012893388:ios:ee284075d36f099f748469',
    messagingSenderId: '785012893388',
    projectId: 'social-circle-qa',
    storageBucket: 'social-circle-qa.appspot.com',
    iosClientId: '785012893388-4b2r25smuhqibqng5aks75ci9s0hlq2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.circle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA1l0CsYs_EDH9QVIxAMf_Ht4iEixUfiE',
    appId: '1:785012893388:ios:ee284075d36f099f748469',
    messagingSenderId: '785012893388',
    projectId: 'social-circle-qa',
    storageBucket: 'social-circle-qa.appspot.com',
    iosClientId: '785012893388-4b2r25smuhqibqng5aks75ci9s0hlq2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.circle',
  );
}
